version: '3.9'
services:
  web-dev:
    build:
      context: ./apps/web-angular
      dockerfile: Dockerfile.dev
    ports:
      - '4200:4200'
    environment:
      - API_URL=http://localhost:3000
    volumes:
      - ./apps/web-angular:/app
  web:
    build:
      context: ./apps/web-angular
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    environment:
      - API_URL=http://localhost:3000
